name: Deploy beta
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - beta
jobs:
  build:

    runs-on: ubuntu-latest
    environment: production
    concurrency: production

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.*'
      - run: yarn
      - run: |
          touch ~/.npmrc && cat >~/.npmrc <<EOL
          //registry.npmjs.org/:_authToken=${{ secrets.npm_token }}
          EOL
      - run: yarn run bootstrap:prod
      - run: |
                git config --global user.email "vladimirmorulus@gmail.com"
                git config --global user.name "CI"
      - run: git status
      - run: publish:prepare-beta
      - run: git status
      - run: publish:beta
      - run: npm run publish:beta
      - run: git push

